### ISSUE TITLE
SQL keyword as alias

### ISSUE THREAD

**Issue by mweisgut** [hyrise/sql-parser#119]
Some TPC-DS queries contain sql keywords as aliases, e.g., `order`. The parser interprets these aliases as sql keywords for the corresponding sql operations.

Example, TPC-DS query 94, netezza dialect:
```sql
select  
   count(distinct ws_order_number) as "order count"
  ,sum(ws_ext_ship_cost) as "total shipping cost"
  ,sum(ws_net_profit) as "total net profit"
from
   web_sales ws1
  ,date_dim
  ,customer_address
  ,web_site
where
    d_date between '2002-5-01' and 
           (cast('2002-5-01' as date) + 60 days)
and ws1.ws_ship_date_sk = d_date_sk
and ws1.ws_ship_addr_sk = ca_address_sk
and ca_state = 'OK'
and ws1.ws_web_site_sk = web_site_sk
and web_company_name = 'pri'
and exists (select *
            from web_sales ws2
            where ws1.ws_order_number = ws2.ws_order_number
              and ws1.ws_warehouse_sk <> ws2.ws_warehouse_sk)
and not exists(select *
               from web_returns wr1
               where ws1.ws_order_number = wr1.wr_order_number)
order by count(distinct ws_order_number)
limit 100;
```

**Comment by cdmh** [comment]
The example shows an error `syntax error, unexpected IDENTIFIER, expecting AND or OR or ')'` on line 12 `(cast('2002-5-01' as date) + 60 days)` It the `days` in `+ 60 days` that is faulting on this query. I think it's a date handling problem, and not a "keyword as alias" problem that is described

**Comment by klauck** [comment]
I would agree. @mweisgut, can we close this issue?

**Comment by cdmh** [comment]
@klauck is the date handling covered by another issue? I think this is  problem, just not as described

**Comment by klauck** [comment]
Yes, we will open another issue for DATE operations.

**Comment by mweisgut** [comment]
> It is the days in + 60 days that is faulting on this query. I think it's a date handling problem, and not a "keyword as alias" problem that is described

Agreed.

> Yes, we will open another issue for DATE operations.

Done: #178
