### ISSUE TITLE
Segmentation fault with printStatementInfo function

### ISSUE THREAD

**Issue by Random90000** [hyrise/sql-parser#130]
I've tried to print info about following query:
```
select count(*) from star where star.ra between 129 and 131 and star.dec between 19 and 21 and -log(0.25*exp(-star.modelmag_u)+0.5*exp(-star.modelmag_g)+0.25*exp(-star.modelmag_r)) < 13.0
```

Parser's **isValid** method said ok, but **printStatementInfo** returned this output:
**SelectStatement
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fields:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count**
Seg fault appears in line 106 sqlhelper.cpp because of null pointer expr->expr.

**Comment by mrks** [comment]
I can't reproduce this, neither on OS X (see below), nor on Linux. Are you (1) using the current master and (2) feeding this into the example binary as below?

As you might have noticed, printStatementInfo does not fully support all expression types. For example, `BETWEEN` gets expressed with its index in `OperatorType`, which is 1. If printing these queries helps you, please consider amending print(Operator)Expression and open a PR for that.

```
> g++ -std=c++1z -I src/ example/example.cpp libsqlparser.so
> ./a.out 'select count(*) from star where star.ra between 129 and 131 and star.dec between 19 and 21 and -log(0.25*exp(-star.modelmag_u)+0.5*exp(-star.modelmag_g)+0.25*exp(-star.modelmag_r)) < 13.0'
Parsed successfully!
Number of statements: 1
SelectStatement
	Fields:
		count
			*
	Sources:
		star
	Search Conditions:
		AND
			AND
				1
					ra
						Table:
							star
					129
					131
				1
					dec
						Table:
							star
					19
					21
			12
				24
					log
						4
							4
								6
									0.25
									exp
										24
											modelmag_u
												Table:
													star
								6
									0.5
									exp
										24
											modelmag_g
												Table:
													star
							6
								0.25
								exp
									24
										modelmag_r
											Table:
												star
				13
```

**Comment by Random90000** [comment]
I've downloaded last version and it works correctly. Thanks a lot!
