### ISSUE TITLE
how to make this parser support Date/Time column?

### ISSUE THREAD

**Issue by hurricane1026** [hyrise/sql-parser#140]
I need Date/Time Data column, how can I add them? or your guys has some dev-plans for this feature?

**Comment by mrks** [comment]
On our side, we have no plans to do so, mostly for time reasons. However, we would be happy to accept a PR for it.

Mostly, it is a question of adding the appropriate keywords to the lexer (flex_lexer.l) and then adding them as column_types to the `CREATE TABLE` statement: https://github.com/hyrise/sql-parser/blob/e3cfc8097546aa9e3d5fb982533594f18ecfdcb9/src/parser/bison_parser.y#L529

**Comment by klauck** [comment]
We will address this in #178
