### ISSUE TITLE
Wrong compiler version requirements in readme?

### ISSUE THREAD

**Issue by msiomkin** [hyrise/sql-parser#148]
c++17 is required to build the project, isn't it? And the minimum versions of gcc and clang that support c++17 are 5 (for both compilers):

https://gcc.gnu.org/projects/cxx-status.html#cxx17
https://clang.llvm.org/cxx_status.html#cxx17

So, why do we have 4.8 and 3.4 in README.md??

```
[vagrant@localhost sql-parser]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[vagrant@localhost sql-parser]$ make
g++ -std=c++1z -Wall -Werror -O3 -fPIC -c -o src/SQLParser.o src/SQLParser.cpp
g++: error: unrecognized command line option ‘-std=c++1z’
make: *** [src/SQLParser.o] Error 1
```

**Comment by mrks** [comment]
Looks like that comment was missed in 5346810e67623f24bebed9c0b343cb9417d47a2b. Thanks for letting us know!
