### ISSUE TITLE
Unable to make after renaming the 'sql-parser' folder

### ISSUE THREAD

**Issue by galbru** [hyrise/sql-parser#16]
I forked your repository and use it as a submodule.
Before I ran make I rename the folder to 'sqlParser' and then run the make command.
Results:
```
[user@localhost sqlParser]$ make
make -C src/parser/
make[1]: Entering directory `/home/user/general/core/external/sqlParser/src/parser'
bison bison_parser.y -v
bison_parser.y:73.20-26: error: syntax error, unexpected {...}
make[1]: *** [bison_parser.cpp] Error 1
make[1]: Leaving directory `/home/user/general/core/external/sqlParser/src/parser'
make: *** [parser] Error 2
[user@localhost sqlParser]$ 
```

**Comment by xarpuia** [comment]
@galbru Maybe you should check the version of bison? It should work with v3.0.2.

**Comment by torpedro** [comment]
Hi @galbru. I would also guess that this is unrelated to the name of the folder. Can you please check the bison version to make sure it is at least version 3.

**Comment by galbru** [comment]
Hi @torpedro . I don't have the environment anymore, so I can't assist. Anyway, Thank you for your help.
