### ISSUE TITLE
support column name: timestamp in create statement

### ISSUE THREAD

**Issue by hl3w22bupt** [hyrise/sql-parser#169]
```
create table test_table (
    timestamp text,
    name text
); 
```
sql parse error.

> is not a valid SQL query. syntax error, unexpected TIMESTAMP, expecting IDENTIFIER (L1:4)

**Comment by cdmh** [comment]
Enclose it in quotes:

    create table test_table (
        “timestamp” text,
        name text
    );

**Comment by hl3w22bupt** [comment]
> Enclose it in quotes:
> 
> ```
> create table test_table (
>     “timestamp” text,
>     name text
> );
> ```

woo，Thanks so much， I tried quote ` and ', both didn't work. quote " works

**Comment by mrks** [comment]
We are following the SQL standard, which uses single quotes for string literals and double quotes for identifiers. [The backtick syntax is a weird MySQL extension.](https://stackoverflow.com/questions/10573922/what-does-the-sql-standard-say-about-usage-of-backtick)
