### ISSUE TITLE
The parser throws an error on square brackets "[ ]"

### ISSUE THREAD

**Issue by samvue2** [hyrise/sql-parser#185]
The square brackets "[ ]" are commonly used to protect schema names, table names, and column names that have spaces in them. The parse somehow could not handle that and will throw an error.

**Comment by Bouncner** [comment]
I haven't seen this syntax before. Is is only used by SQL server? Looks like it is not part of any SQL specification.

**Comment by samvue2** [comment]
Yes, that is used by SQL Server. I just looked at MySQL as well, the "`" character is used in this case. But the parser has a problem with that too. There may not be any SQL standard on that. But practically we need a way to handle the table names and column names with spaces in them. Appreciate the help on this issue!

**Comment by Bouncner** [comment]
I don't think implementing a product-specific syntax is within the scope of Hyrise's parser. Especially -- if I am not mistaken -- since the SQL standard allows to delimit such cases with double quotes, which also supported by SQL Server.

PS: you don't need to create a new account every time. ;)

**Comment by samvue2** [comment]
That's good to know. We'll give it a try by replacing square brackets and tilde sign with double quotes before sending the queries to the parser. I'll close this issue afterwards. Thank you.

**Comment by mweisgut** [comment]
> That's good to know. We'll give it a try by replacing square brackets and tilde sign with double quotes before sending the queries to the parser. I'll close this issue afterwards. Thank you.

Do you have any updates on that?

**Comment by samvue2** [comment]
After replacing the square brackets with double quotes, the parser works fine. I'll close the issue for now. Thanks.
