### ISSUE TITLE
Using SQLParser to parse a SQL with IF failed

### ISSUE THREAD

**Issue by heheave** [hyrise/sql-parser#204]
I got a invalid return code when i used SQLParser to parse a SQL with IF statement(like "select if(1=1, 1, 2) from abc"). 
Did i use it in a wrong way?

**Comment by Bouncner** [comment]
Please have a look at case statements, which are supported.

https://www.w3schools.com/sql/sql_case.asp

**Comment by Bouncner** [comment]
I am not aware of an SQL dialect that uses `if` in any form.

`case` should cover these cases and is part of SQL at least since the 92 specification if  I am  not mistaken.

**Comment by heheave** [comment]
I got it. `IF(condition, value_if_true, value_if_false)` is actually a dialect supported by MYSQL. Thanks for your reply.

**Comment by Bouncner** [comment]
Ah, interesting. Wasn't aware of this MySQL syntax. Good to know.

Thanks for the notice.
