### ISSUE TITLE
Failed to compile the source code

### ISSUE THREAD

**Issue by crspecter** [hyrise/sql-parser#227]
when i compile source code get erros
!3182 # make
g++ -shared -o libsqlparser.so src/SQLParser.o src/SQLParserResult.o src/parser/bison_parser.o src/parser/flex_lexer.o src/sql/CreateStatement.o src/sql/Expr.o src/sql/PrepareStatement.o src/sql/SQLStatement.o src/sql/statements.o src/util/sqlhelper.o
src/parser/flex_lexer.o: In function `yyerror(char const*)':
flex_lexer.cpp:(.text+0x1070): multiple definition of `yyerror(char const*)'
src/SQLParser.o:SQLParser.cpp:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:67: libsqlparser.so] Error 1

**Comment by dey4ss** [comment]
Can you please provide some system/compiler information?

**Comment by crspecter** [comment]
flex & bison like this
!3002 # flex --version
flex 2.5.39

root@dba-dev-drc-dev-tc4-g1-9:/home/dmadmin  01:42 PM Thu Jan 12  
!3003 # bison --version
bison (GNU Bison) 3.8.2
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
