### ISSUE TITLE
How do keyword conflicts need to be resolved

### ISSUE THREAD

**Issue by nIxedoahz** [hyrise/sql-parser#228]
select aa from table;

error:
 Given string is not a valid SQL query.
 syntax error, unexpected TABLE, expecting IDENTIFIER or '(' (L0:15)

**Comment by dey4ss** [comment]
Hi @nIxedoahz, in ANSI SQL, you can use double quotation marks (`"`):
```sql
SELECT "column" FROM "table";
```
See also the [Postgres documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).

**Comment by nIxedoahz** [comment]
> Hi @nIxedoahz, in ANSI SQL, you can use double quotation marks (`"`):
> 
> ```sql
> SELECT "column" FROM "table";
> ```
> 
> See also the [Postgres documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).

Is the keyword as listed or table name cannot be resolved can support

**Comment by dey4ss** [comment]
I am not sure if I totally get your question. `table` is a [reserved SQL keyword](https://www.postgresql.org/docs/current/sql-keywords-appendix.html). These keywords form the structure of SQL statements and have special meaning. Thus, the parser complains that you use the reserved keyword `table` where it expects an identifier (e.g., a table name or a view name). However, you can explicitly tell it to treat `table` as an identifier ba wrapping it in double quotation marks, as I showed before. This is not a special feature or limitation of our parser, but specified ba the SQL standard. There are great resources available online if you want to look into this.
Does this answer your question? If not, feel free to provide more explanation about your issue.
