### ISSUE TITLE
SQL Optimizer

### ISSUE THREAD

**Issue by kabicm** [hyrise/sql-parser#237]
Is this parser also able to optimize the SQL queries (logical optimizer)?

Thanks!

**Comment by Bouncner** [comment]
Hi Marko,
the parser really only parses SQL. Nothing more.
But the parser is part of our research database system Hyrise which has a logical query optimizer with all sorts of query optimizations (see here: https://github.com/hyrise/hyrise).

**Comment by Bouncner** [comment]
Closing this issue for now. Feel free to re-open if you have any questions.
