### ISSUE TITLE
ERROR when alias as "file"

### ISSUE THREAD

**Issue by TikaFlow** [hyrise/sql-parser#241]
The command line output:

```bash
[~/temp/sql-parser/example] # LD_LIBRARY_PATH=. ./example "select col3 as user, col5 as size, col9 as file from abc limit 3" 
Given string is not a valid SQL query.
syntax error, unexpected FILE, expecting IDENTIFIER (L0:43)
# but when I alias as file1 or any other:
[~/temp/sql-parser/example] # LD_LIBRARY_PATH=. ./example "select col3 as user, col5 as size, col9 as file1 from abc limit 3"
Parsed successfully!
Number of statements: 1
SelectStatement
        Fields:
                col3
                        Alias
                                user
                col5
                        Alias
                                size
                col9
                        Alias
                                file1
        Sources:
                abc
        Limit:
                3  
```

Does 'file' have a special meaning in the program?

**Comment by Bouncner** [comment]
`FILE` is a keyword in Postgres. Can you try quoting it?

**Comment by TikaFlow** [comment]
Oh sorry I don't know because I haven't used Postgres before.
I tried quote it and works well.

But there's one small regret that double quotes needs to be escaped and single quotes is not soupported.

**Comment by Bouncner** [comment]
> Oh sorry I don't know because I haven't used Postgres before. I tried quote it and works well.
> 
> But there's one small regret that double quotes needs to be escaped and single quotes is not soupported.

I don’t have a good link at hand but please be aware of the different meanings of single and double quotes in most (or all!??) SQL dialects.

**Comment by TikaFlow** [comment]
> > Oh sorry I don't know because I haven't used Postgres before. I tried quote it and works well.
> > But there's one small regret that double quotes needs to be escaped and single quotes is not soupported.
> 
> I don’t have a good link at hand but please be aware of the different meanings of single and double quotes in most (or all!??) SQL dialects.

Escaping double quotes doesn't affect my usage, just a little obsessive-compulsive. Anyway, thanks for the explanation.
