### ISSUE TITLE
Parser fails if a column is called "locked"

### ISSUE THREAD

**Issue by kingkero** [hyrise/sql-parser#243]
To demonstrate quickly, I just updated an existing test:

```diff
 TEST(SelectSchemaTest) {
-  TEST_PARSE_SINGLE_SQL("SELECT grade FROM some_schema.students;", kStmtSelect, SelectStatement, result, stmt);
+  TEST_PARSE_SINGLE_SQL("SELECT grade, locked FROM some_schema.students;", kStmtSelect, SelectStatement, result, stmt);

   ASSERT(stmt->fromTable);
   ASSERT_EQ(std::string(stmt->fromTable->schema), "some_schema");
 }
```

Results in:

```bash
{ running} SelectSchemaTest
{  failed} SelectSchemaTest
           Assertion failed: result.isValid()
           test//select_tests.cpp:158
```

With backticks I get

```bash
[SQL-Lexer-Error] Unknown Character: `
```

It seems that since MySQL 8.0.1 `LOCKED` is a [reserved keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html), but even with with 8.0.27 I could easily use it without backticks in a query ([see fiddle](https://sqlfiddle.com/mysql/online-compiler?id=26c32048-81e7-48a4-8516-bf1058497501)).

**Comment by Bouncner** [comment]
Since it is a keyword (even though non-reserved) in Postgres (which is the SQL dialect that are following), the error does not surprise me.
You should be able to normally quote the keyword and still use it as a columns name (I cannot test it right now). But ``` is MySQL-only and not following SQL standard. Can you try `"`?

**Comment by klauck** [comment]
`"` and `'` work.
You can also use the `example` executable to quickly test parsing specific statements:

`./example/example 'SELECT grade, "locked" FROM some_schema.students;'`
Parsed successfully!
Number of statements: 1
SelectStatement
	Fields:
		grade
		locked
	Sources:
		students
			Schema
				some_schema

**Comment by kingkero** [comment]
Thank you both for the quick replies!

Can confirm that it works with quotes (wasn't aware that backticks are MySQL-only)
