### ISSUE TITLE
MSVC build

### ISSUE THREAD

**Issue by occash** [hyrise/sql-parser#38]
It seems that it is possible to build sql-parser with msvc (I built it with msvc 2015), however there is no <unistd.h> on Windows.

**Comment by chencang1980** [comment]
replace unistd.h with io.h works

**Comment by cdmh** [comment]
No cpp file is cited for this include, but I build `origin/master` code with MSVC2019 without modification. A `grep` of the source tree find no `unistd.h` outside of the flex generated source, which is appropriately guarded.

I think this can be closed?
