### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by EvilMcJerkface** [hyrise/sql-parser#51]
[sql-parser/LICENSE](https://github.com/hyrise/sql-parser/blob/6d3cd804524a66835d0c46db04130108e78745b9/LICENSE) currently states at the top:

```
This computer program can be used by anyone in accordance with the OpenSource
licence of the Hasso-Plattner Institute. Its terms of use can be downloaded
under the URL https://github.com/hyrise/hyrise/blob/master/LICENSE
```

and then goes on to spell out the terms of the Hasso-Plattner OpenSource license.  However, the referenced [hyrise/LICENSE](https://github.com/hyrise/hyrise/blob/909120dd2bcb77950a661dd87718cb1f8bc8950d/LICENSE) is the standard MIT license.

Could you please clarify which license - Hasso-Plattner OpenSource or MIT - currently applies to sql-parser?  Thanks!

**Comment by torpedro** [comment]
Thanks for pointing this out. We have switched the license for the sql-parser to the MIT license.
