### ISSUE TITLE
Unable to use in Windows

### ISSUE THREAD

**Issue by mmbspk** [hyrise/sql-parser#7]
I tried to use the parser in Windows with Visual studio 2012. I was finally somehow succeeded in compiling the basic project. But the flex_lexer.cpp file throws the fatal error that the limit of nested conditions exceeded. i.e. "flex_lexer.l(215): fatal error C1061: compiler limit : blocks nested too deeply"
Can you please help me out here what i am missing and how can i make this thing to work.

**Comment by torpedro** [comment]
Hi! Thanks for trying to build it on Windows. Unfortunately we've never tested it on Windows.
This nesting limit within the Visual Studio compiler seems to be a hard constraint within the compiler and I don't know of any way to decrease the nesting levels that flex and bison create.

What I'd recommend to run it on Windows is using a different compiler. We've only tested the SQL parser on Linux with the GCC compiler. You can find a GCC compiler for Windows within the Cygwin project (https://cygwin.com/). It would be really great if you could try to run it with that compiler on Windows again.

I have no Windows setup to test it myself, but I will make a note within our documentation as to which development setups and compiler versions have been tested.

Thanks!
Pedro

**Comment by rressi** [comment]
# Possible solution

If you need to integrate this library inside a Visual Studio project, another viable option that may work under windows is the following:
- download MSYS2 that is a much more modern evolution of cygwin.
- launch MSYS2 terminal (there is a .bat file for it at the root folder, usually `C:\msys64`).
- from the MSYS2 terminal install `mingw64` if you want to target x64 or  `mingw32` for x86.
- also install `GNU make` and `git.
- open a MINGW64/32 terminal (there is a .bat file for it at the root folder, usually `C:\msys64`).
- compile this project with `make` and `make test` to validate it. You may need some minor fixes.
- add a new layer with header files that does not export any STL container, the layer should expose only the parts of this library you are interested to. Should use pure virtual interfaces with factory methods, a true API as opposed to this that is a mini-framework.
- then you can use this new library from Visual Studio, any version.

**Comment by torpedro** [comment]
Hi Riccardo, thanks for the great guide on how to use the library on Windows!

It would be great if we could incorporate some of your findings into the repository, so that we can make it as easy as possible for users on Windows. Possibly at least for use with MSYS2.
If you want, feel free to create a pull request to adapt the Makefile to also work on Windows. Possibly also adapting the example project. If you don't have time, let me know and I'll look into it.

In the meantime I'll think about how to include your findings in our documentation.

Thanks!

**Comment by rressi** [comment]
Adapting your Makefile to support Windows (and OSX) is really easy and I
will create soon a pull request for it so that more people could enjoy your
work.


On Sunday, 13 March 2016, Pedro Flemming <notifications@github.com> wrote:

> Hi Riccardo, thanks for the great guide on how to use the library on
> Windows!
>
> It would be great if we could incorporate some of your findings into the
> repository, so that we can make it as easy as possible for users on
> Windows. Possibly at least for use with MSYS2.
> If you want, feel free to create a pull request to adapt the Makefile to
> also work on Windows. Possibly also adapting the example project. If you
> don't have time, let me know and I'll look into it.
>
> In the meantime I'll think about how to include your findings in our
> documentation.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyrise/sql-parser/issues/7#issuecomment-195963855>.
>


-- 
Contacts: +41 78 842 39 16 (Swiss mobile phone)

**Comment by Amilelne** [comment]
I'm sorry,I'm a newer in learning c++,and I don't know where and how to create an API.In your solution,you said "Creating an API that wraps this library that does not expose anything related with STLand that just expose C++ free functions exported without manglin thanks to the extern "C" clause."Can you help me?

**Comment by cdmh** [comment]
`origin/master` compiles cleanly without modification with MSVC2019

I think this can be closed?
