### ISSUE TITLE
Arbitrary text allowed behind SQL query

### ISSUE THREAD

**Issue by mrks** [hyrise/sql-parser#74]
<pre>
(debug)> SELECT * FROM t <strong>ICANDOMAGICHERE</strong>;
=== Columns
|       a|       b|
|     int|     int|
=== Chunk 0 ===
|   12345|       1|
|     123|       2|
|    1234|       3|
===
3 rows total (COMPILE: 13 µs, EXECUTE: 207 µs (wall time))
(debug)> SELECT * FROM t WHERE a=b <strong>ICANDOMAGICHERE</strong>;
SQL query not valid.
SQL query:
==========
SELECT * FROM t WHERE a=b <strong>ICANDOMAGICHERE</strong>;
                          ^=== ERROR HERE!
==========
Error line: 0
Error column: 26
Error message: syntax error, unexpected IDENTIFIER, expecting $end
</pre>

**Comment by adamyi** [comment]
This is not a bug. `ICANDOMAGICHERE` is an alias of the table `t`.

See https://en.wikipedia.org/wiki/Alias_(SQL).

> Using a table alias:
> `SELECT D.DepartmentName FROM Department AS D`
> 
> We can also write the same query like this (Note that the AS clause is omitted this time):
> `SELECT D.DepartmentName FROM Department D`
>

**Comment by mrks** [comment]
Ah, of course. What a stupid mistake. Thank you for correcting me!
