### ISSUE TITLE
LIMIT with Expression not supported

### ISSUE THREAD

**Issue by mrzzzrm** [hyrise/sql-parser#91]
However `SELECT * FROM t LIMIT 1 + 2` works in Postgres

**Comment by mrzzzrm** [comment]
Lame. I was so happy we could support `SELECT int_float.a AS x FROM int_float LIMIT 3 + (SELECT MIN(b) FROM int_float2);` on the expression side :( :( Close it if you want to. I think the change to the SQLParser would be minimal and on the Hyrise side it's also in with maybe a dozen lines of overhead

**Comment by mrks** [comment]
How about `SELECT int_float.a AS x FROM int_float LIMIT int_float.a;`? :D

**Comment by mrzzzrm** [comment]
MS SQL also supports Expressions in their TOP clause

**Comment by mrzzzrm** [comment]
> How about SELECT int_float.a AS x FROM int_float LIMIT int_float.a;? :D

Won't work and the Expression system in Hyrise would faithfully report that you can't refer to Columns in that location

**Comment by mrzzzrm** [comment]
SQLite supports it as well. C'mon, let me have some fun? :smile:

**Comment by mrks** [comment]
If you want to and it's not too much additional code, go for it.
